# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .v_1_delete_token_response_object import V1DeleteTokenResponseObject


class V1DeleteTokenResponse(UniversalBaseModel):
    tokens: typing.Optional[typing.List[V1DeleteTokenResponseObject]] = pydantic.Field(default=None)
    """
    Tokens data for Delete
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
