# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .v_1_record_response_object import V1RecordResponseObject


class V1UpdateResponse(UniversalBaseModel):
    records: typing.Optional[typing.List[V1RecordResponseObject]] = pydantic.Field(default=None)
    """
    List of updated records with skyflow ID, tokens, data, and any partial errors
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
