import json
from skyflow.service_account import (
    generate_bearer_token,
    generate_bearer_token_from_creds,
    is_expired,
)

file_path = '<YOUR_CREDENTIALS_FILE_PATH>'
bearer_token = ''

skyflow_credentials = {
    'clientID': '<YOUR_CLIENT_ID>',
    'clientName': '<YOUR_CLIENT_NAME>',
    'tokenURI': '<YOUR_TOKEN_URI>',
    'keyID': '<YOUR_KEY_ID>',
    'privateKey': '<YOUR_PRIVATE_KEY>',
}
credentials_string = json.dumps(skyflow_credentials)

# Scoped tokens are generated by assigning specific roles for access control.
options = {'role_ids': ['<YOUR_ROLE_ID1>', '<YOUR_ROLE_ID2>']}


def get_scoped_bearer_token_from_file_path():
    global bearer_token
    try:
        if not is_expired(bearer_token):
            return bearer_token
        token, _ = generate_bearer_token(file_path, options)
        bearer_token = token
        return bearer_token
    except Exception as e:
        print(f'Error generating token from file path: {str(e)}')


def get_scoped_bearer_token_from_credentials_string():
    global bearer_token
    try:
        if not is_expired(bearer_token):
            return bearer_token
        token, _ = generate_bearer_token_from_creds(credentials_string, options)
        bearer_token = token
        return bearer_token
    except Exception as e:
        print(f'Error generating token from credentials string: {str(e)}')


print('Scoped Token (using file path):', get_scoped_bearer_token_from_file_path())
print('Scoped Token (using credentials string):', get_scoped_bearer_token_from_credentials_string())
