name: Public Beta Release

on:
  push:
    tags: '*.*.*b*'
    paths-ignore:
      - "setup.py"
      - "*.yml"
      - "*.md"
      - "skyflow/utils/_version.py"

permissions:
  contents: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/shared-build-and-deploy.yml
    with:
      ref: ${{ github.ref_name }}
      tag: 'beta'
    secrets: inherit
