name: Internal Release

on:
  push:
    tags-ignore:
      - '*.*'
    paths-ignore:
      - "setup.py"
      - "*.yml"
      - "*.md"
      - "skyflow/utils/_version.py"
      - "samples/**"
    branches:
      - release/*

jobs:
  build-and-deploy:
    uses: ./.github/workflows/shared-build-and-deploy.yml
    with:
      ref: ${{ github.ref_name }}
      is-internal: true
    secrets: inherit
      
