name: Internal Release

on:
  push:
    tags-ignore:
      - '*.*'
    paths-ignore:
      - "setup.py"
      - "*.yml"
      - "*.md"
      - "skyflow/utils/_version.py"
    branches:
      - release/*

jobs:
  build-and-deploy:
    uses: ./shared-build-and-deploy.yml@main
    with:
      ref: ${{ github.ref_name }}
      artifactory-username: ${{ secrets.JFROG_USERNAME }}
      artifactory-password: ${{ secrets.JFROG_PASSWORD }}
      is-internal: true
