name: Public Release

on:
  push:
    tags: "*.*.*"
    paths-ignore:
      - "setup.py"
      - "*.yml"
      - "*.md"
      - "skyflow/utils/_version.py"

jobs:
  build-and-deploy:
    uses: ./.github/workflows/shared-build-and-deploy.yml
    with:
      ref: main
      is-internal: false
    secrets: inherit
