name: Public Release

on:
  push:
    tags: "*.*.*"
    paths-ignore:
      - "setup.py"
      - "*.yml"
      - "*.md"
      - "skyflow/version.py"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_ACTIONS }}
          ref: main
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0

      - name: Bump Version
        run: |
          chmod +x ./ci-scripts/bump_version.sh
          ./ci-scripts/bump_version.sh "${{ steps.previoustag.outputs.tag }}"

      - name: Commit changes
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git add setup.py
          git add skyflow/version.py
          git commit -m "[AUTOMATED] Public Release - ${{ steps.previoustag.outputs.tag }}"
          git push origin
          
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PUBLISH_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
