name: Public Release

on:
  push:
    tags: "*.*.*"
    paths-ignore:
      - "*/setup.py"
      - "*.yml"
      - "*.md"
      - "*/skyflow/utils/_version.py"

jobs:
  build-and-deploy:
    strategy:
      matrix:
        include:
          - variant: v2
            tag-prefix: ''
          - variant: v3
            tag-prefix: 'flowvault-'
    if: (matrix.variant == 'v3' && startsWith(github.ref_name, 'flowvault-')) || (matrix.variant == 'v2' && !startsWith(github.ref_name, 'flowvault-'))
    uses: ./.github/workflows/shared-build-and-deploy.yml
    with:
      ref: main
      tag: 'public'
      variant: ${{ matrix.variant }}
      tag-prefix: ${{ matrix.tag-prefix }}
    secrets: inherit
